<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="0" total="3" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="16579" started-at="2018-12-14T06:40:11Z" finished-at="2018-12-14T06:40:27Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="16579" started-at="2018-12-14T06:40:11Z" finished-at="2018-12-14T06:40:27Z">
      <class name="testcase.TC02_TC03_TC05">
        <test-method status="PASS" signature="beforeClass()[pri:0, instance:testcase.TC02_TC03_TC05@5b275dab]" name="beforeClass" is-config="true" duration-ms="9823" started-at="2018-12-14T06:40:11Z" finished-at="2018-12-14T06:40:20Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method status="PASS" signature="Initdriver()[pri:0, instance:testcase.TC02_TC03_TC05@5b275dab]" name="Initdriver" is-config="true" duration-ms="45" started-at="2018-12-14T06:40:20Z" finished-at="2018-12-14T06:40:20Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Initdriver -->
        <test-method status="PASS" signature="TC02()[pri:0, instance:testcase.TC02_TC03_TC05@5b275dab]" name="TC02" duration-ms="1541" started-at="2018-12-14T06:40:20Z" description="Test Login with blank user name" finished-at="2018-12-14T06:40:22Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC02 -->
        <test-method status="PASS" signature="Initdriver()[pri:0, instance:testcase.TC02_TC03_TC05@5b275dab]" name="Initdriver" is-config="true" duration-ms="5" started-at="2018-12-14T06:40:22Z" finished-at="2018-12-14T06:40:22Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Initdriver -->
        <test-method status="FAIL" signature="TC03()[pri:0, instance:testcase.TC02_TC03_TC05@5b275dab]" name="TC03" duration-ms="1000" started-at="2018-12-14T06:40:22Z" description="Test Login with invalid password" finished-at="2018-12-14T06:40:23Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [There was a problem with your login and/or errors exist in your form.] but found [Invalid username or password. Please try again.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [There was a problem with your login and/or errors exist in your form.] but found [Invalid username or password. Please try again.]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at testcase.TC02_TC03_TC05.TC03(TC02_TC03_TC05.java:55)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC03 -->
        <test-method status="PASS" signature="Initdriver()[pri:0, instance:testcase.TC02_TC03_TC05@5b275dab]" name="Initdriver" is-config="true" duration-ms="3" started-at="2018-12-14T06:40:23Z" finished-at="2018-12-14T06:40:23Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Initdriver -->
        <test-method status="FAIL" signature="TC05()[pri:0, instance:testcase.TC02_TC03_TC05@5b275dab]" name="TC05" duration-ms="3543" started-at="2018-12-14T06:40:23Z" description="Check Login attempts error - more than 3 times" finished-at="2018-12-14T06:40:27Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [You have used 4 out of 5 login attempts. After all 5 have been used, you will be unable to login for 15 minutes.] but found [Invalid username or password. Please try again.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [You have used 4 out of 5 login attempts. After all 5 have been used, you will be unable to login for 15 minutes.] but found [Invalid username or password. Please try again.]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at testcase.TC02_TC03_TC05.TC05(TC02_TC03_TC05.java:73)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC05 -->
        <test-method status="PASS" signature="afterClass()[pri:0, instance:testcase.TC02_TC03_TC05@5b275dab]" name="afterClass" is-config="true" duration-ms="591" started-at="2018-12-14T06:40:27Z" finished-at="2018-12-14T06:40:27Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClass -->
      </class> <!-- testcase.TC02_TC03_TC05 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
